---
title: "Final Project"
date: '2022-11-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
```


## Load Data

```{r load_data}
data_2020 <- read.csv("data/sentiment_country_2020.csv")
data_2021 <- read.csv("data/sentiment_country_2021.csv")
```


```{r viewing scores}
view(data_2020)
view(data_2021)
```


## Visualize Data

```{r comparision 2020 and 2021}

#2020

data_2020$DATE=as.Date(data_2020$DATE)

data_2020$Month <- months(data_2020$DATE)
data_2020$Year <- format(data_2020$DATE,format="%y")

data_2020<-data_2020 %>% filter(!is.na(data_2020$SCORE))

monthly2020=data_2020 %>% 
  group_by(Month,Year) %>% 
  summarise_at(vars(SCORE),
               list(Score=mean))

monthly2020$Month=factor(monthly2020$Month, levels = month.name)


#2021

data_2021$DATE=as.Date(data_2021$DATE)

data_2021$Month <- months(data_2021$DATE)
data_2021$Year <- format(data_2021$DATE,format="%y")

data_2021<-data_2021 %>% filter(!is.na(data_2021$SCORE))

monthly2021=data_2021 %>% 
  group_by(Month,Year) %>% 
  summarise_at(vars(SCORE),
               list(Score=mean))

monthly2021$Month=factor(monthly2021$Month, levels = month.name)



monthly <- rbind(monthly2020,monthly2021)

monthly

monthly$Year[monthly$Year == "20"] <- "2020"
monthly$Year[monthly$Year == "21"] <- "2021"

ggplot (data=monthly, aes(Month, Score, group = Year, color = Year))+
  geom_point()+geom_line()+
  theme_bw()


```


```{r avg score 2020}

avg_data_2020<-data_2020 %>%
  group_by(NAME_0) %>%
  summarize(
    avg_score_2020 = mean(SCORE, na.rm = TRUE)
    )

avg_data_2021<-data_2021 %>%
  group_by(NAME_0) %>%
  summarize(
    avg_score_2021 = mean(SCORE, na.rm = TRUE)
    )

names(avg_data_2020)[names(avg_data_2020) == "NAME_0"] <- "region"
names(avg_data_2021)[names(avg_data_2021) == "NAME_0"] <- "region"

```



```{r range of scores 2020}

ggplot(data = data_2020, aes(x=SCORE)) + 
  geom_histogram(binwidth = 0.01, fill = "lightblue")+ 
  ylab("Frequency") + 
  xlab("sentiment score") +
  ggtitle("Distribution of Sentiment scores of the tweets")+
  theme_bw()

ggplot(data = data_2021, aes(x=SCORE)) + 
  geom_histogram(binwidth = 0.01, fill = "lightblue")+ 
  ylab("Frequency") + 
  xlab("sentiment score") +
  ggtitle("Distribution of Sentiment scores of the tweets")+
  scale_fill_viridis()+
  theme_bw()

```

```{r world map plot}
mapdata <- map_data("world") 

#changing USA to United States
mapdata$region[mapdata$region == "USA"] <- "United States"

#changing UK to United Kingdom
mapdata$region[mapdata$region == "UK"] <- "United Kingdom"

mapdata <- left_join(mapdata, avg_data_2020, by="region")
mapdata <- left_join(mapdata, avg_data_2021, by="region")

mapdata1<-mapdata %>% filter(!is.na(mapdata$avg_score_2020))
mapdata1<-mapdata %>% filter(!is.na(mapdata$avg_score_2021))


map1<-ggplot(mapdata1, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = avg_score_2020), color = "black")

map2<-ggplot(mapdata1, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = avg_score_2021), color = "black")

library(viridis)

map1 <- map1 + scale_fill_gradient(name = "avg score")+
  theme(axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank()) +
scale_fill_viridis()
map1

map2 <- map2 + scale_fill_gradient(name = "avg score")+
  theme(axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())+
scale_fill_viridis()
map2
```


```{r loading gdp data}

gdp_2020 <- read_csv("gdp_2020.csv")

gdp_2021 <- read_csv("gdp_2021.csv")

gdp_2020 <- gdp_2020[c(1,5)]
gdp_2021 <- gdp_2021[c(1,5)]

names(gdp_2020)[names(gdp_2020) == "Country Name"] <- "region"
names(gdp_2021)[names(gdp_2021) == "Country Name"] <- "region"

names(gdp_2020)[names(gdp_2020) == "2020 [YR2020]"] <- "gdp"
names(gdp_2021)[names(gdp_2021) == "2021 [YR2021]"] <- "gdp"


names(data_2020)[names(data_2020) == "NAME_0"] <- "region"
names(data_2021)[names(data_2021) == "NAME_0"] <- "region"

data_2020 <- left_join(data_2020, gdp_2020, by="region")
data_2021 <- left_join(data_2021, gdp_2021, by="region")

data_total <- rbind(data_2020,data_2021)
#view(data_total)

sentiment_data <- data_total

```




```{r compare_variables}

#removing missing values
data_total<-data_total[!(data_total$gdp==".."),]

data_total$gdp <- as.numeric(as.character(data_total$gdp))

data_total$gdp = (data_total$gdp) / 10000000000000

data_total<-data_total %>% filter(!is.na(data_total$gdp))

#comparing both the variables
lgdp=log(data_total$gdp)
ggplot(data = data_total, aes(x = lgdp , y = SCORE))+ 
  geom_point() + 
  geom_smooth(method = "lm")+
  theme_bw()

attach(data_total)
m1=lm(SCORE~gdp)
summary(m1)
```
```{r regression1 DAILY}

library(brms)
dv <- brm(formula = SCORE~gdp, data=data_total, family=gaussian , refresh=0)

```

```{r sum_model1 DAILY}
summary(dv)
```

```{r plot_uncertainty_coef1 DAILY}
attach(data_total)
uncertainty_coef<-as_draws_df(dv, variable = "b_gdp")
ggplot(uncertainty_coef, aes(x=b_gdp))+geom_density()+labs(title= "Uncertainty in regression coefficient",
                                                                  x="Regression Coefficient",
                                                                  y="Uncertainty")+
  theme_bw()
```

```{r plot_effects1 DAILY}
conditional_effects(dv,effects="gdp")
```


```{r internet users}
internet_users <- read.csv("internet_users.csv")

internet_users <- internet_users[c(2,3)]

internet_users<-internet_users %>% filter(!is.na(internet_users$X.1))

internet_users<-internet_users %>%  filter(!row_number() %in% c(1, 2, 3, 4))

names(internet_users)[names(internet_users) == "X.1"] <- "region"
names(internet_users)[names(internet_users) == "X.2"] <- "users"

df<-left_join(internet_users,data_total, by="region")

df<-df %>% filter(!is.na(df$SCORE))

df$users <- as.numeric(as.character(df$users))

ggplot(data = df, aes(x = users , y = SCORE))+ 
  geom_point() + 
  geom_smooth()+
  theme_bw()

```

```{r regression2}

library(brms)
dv2 <- brm(formula = SCORE ~ users, data=df, family=gaussian ,refresh=0)

```

```{r plot_reg_coefs2}
draws_fit <- as_draws_df(dv2)
posterior::summarize_draws(draws_fit)
```

```{r cond_eff_coefs2}
conditional_effects(dv2)
```

```{r regression3}
dv3 <- brm(formula = SCORE~gdp+users, data=df, family=gaussian ,refresh=0)
```
```{r plot_reg_coefs3}
draws_fit <- as_draws_df(dv3)
posterior::summarize_draws(draws_fit)
```
```{r cond_eff_coefs3}
conditional_effects(dv3)
```

```{r regression4}
dv4 <- brm(formula = SCORE~gdp*users, data=df, family=gaussian ,refresh=0)
```

```{r plot_reg_coefs4}
draws_fit <- as_draws_df(dv4)
posterior::summarize_draws(draws_fit)
```

```{r cond_eff_coefs4}
conditional_effects(dv4)
```

```{r load and clean average hours}
average_hours <- read.csv("average_hours.csv")


average_hours <- average_hours[c(1,3,4,76,77)]
average_hours<-average_hours %>%  filter(!row_number() %in% c(1, 2, 3))
average_hours <- dplyr::filter(average_hours, X.2 %in% c("Average Hours Worked"))
average_hours <- average_hours[c(2,4,5)]
names(average_hours)[names(average_hours) == "X.1"] <- "region"
names(average_hours)[names(average_hours) == "X.74"] <- "averageHours"
names(average_hours)[names(average_hours) == "X.75"] <- "averageHours"
view(average_hours)

avg20 <- average_hours[c(1,2)]
avg21 <- average_hours[c(1,3)]

avg20['Year'] = '20'
avg21['Year'] = '21'

```

```{r comparing hours and sentiment scores}

avg_20 <- dplyr::filter(data_total, Year %in% c("20"))
avg_21 <- dplyr::filter(data_total, Year %in% c("21"))

avg_20 <- left_join(avg_20, avg20, by=c("region","Year"))
avg_21 <- left_join(avg_21, avg21, by=c("region","Year"))

data_total <- rbind(avg_20,avg_21)

data_total<- data_total %>% filter(!is.na(data_total$averageHours))

data_total$averageHours <- as.numeric(gsub(",","",data_total$averageHours))

data_total$averageHours <- data_total$averageHours/1000

ggplot(data = data_total, aes(x = averageHours , y = SCORE))+ 
  geom_point() + 
  geom_smooth()+
  theme_bw()

```
```{r regression5}
dv5 <- brm(formula = SCORE~averageHours, data=data_total, family=gaussian ,refresh=0)
```

```{r plot_reg_coefs5}
draws_fit <- as_draws_df(dv5)
posterior::summarize_draws(draws_fit)
```

```{r cond_eff_coefs5}
conditional_effects(dv5)
```

